# Generated by Django 4.0.3 on 2022-05-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_imagemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
