# Generated by Django 4.0.3 on 2022-05-07 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_imagemodel_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='image_url',
        ),
    ]
