# Generated by Django 4.0.3 on 2022-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_imagemodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_200px',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_400px',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
